---

- hosts: all
  become: true
  tasks:

# refactor 2 plays down to 1
# using the generic OS package manager "package" and variables denoted by double curly brackets {{}}. Variables are hard defined in inventory file.

  - name: install apache and php packages
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
