---

- hosts: all
  become: true
  tasks:

  - name: remove apache2 package
    apt:
      name: apache2
      state: absent

  - name: remove apache php support
    apt:
      name: libapache2-mod-php
      state: absent
